apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api-app
  name: user-api-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/user-api-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-api-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}